### ISSUE TITLE
Missing `Content-Length` header, resulting in INVALID_HEADERS response

### ISSUE THREAD

**Issue by benwr** [libninjacom/plaid-rs#15]
When calling `PlaidClient::link_token_create`, this library seems to send a request with no `Content-Length` header.

Using the `LoggingMiddleware`, I observe the following Request:

`Request: Request { method: POST, uri: https://sandbox.plaid.com/link/token/create?[...], version: HTTP/1.1, headers: {"user-agent": "httpclient/0.19.2", "plaid-client-id": "[...]", "plaid-secret": "[...]", "plaid-version": "2020-09-14"}, body: InMemory(Empty) }`

Which results in the following response from Plaid:

```
{
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_HEADERS",
  "error_message": "The Content-Length header is required for all http methods except: OPTIONS, DELETE, GET",
  "error_type": "INVALID_REQUEST",
  "request_id": "[...]",
  "suggested_action": null
}
```

**Comment by benwr** [comment]
A couple months ago I was using this library (I think version 6.0) to get link tokens, without observing this issue. I don't remember if I was doing it exactly the same way, so I'm not sure if this is a change in the library since then or a change in my usage.

**Comment by benwr** [comment]
I confirmed that this still works in 6.0

**Comment by kurtbuilds** [comment]
Thank you.

This was an issue in the codegen, where parameters were getting passed in the URL instead of the body for some requests.

I regenerated the library with the latest libninja, and confirmed that `link_token_create` is working with this example (a more comprehensive, though autogenerated, example is in the repo itself)

```rust
#![allow(unused_imports)]
use plaid::PlaidClient;
use plaid::model::*;
use plaid::request::LinkTokenCreateRequired;
#[tokio::main]
async fn main() {
    let client = PlaidClient::from_env();
    let args = LinkTokenCreateRequired {
        client_name: "your client name",
        country_codes: &["us"],
        language: "en",
        user: LinkTokenCreateRequestUser {
            client_user_id: "your client user id".to_owned(),
            ..LinkTokenCreateRequestUser::default()
        }
    };
    let response = client
        .link_token_create(args)
        .products(&["auth", "transactions"])
        .await
        .unwrap();
    println!("{:#?}", response);
}
```

With the new version, note that the PLAID_ENV variable just takes an environment, rather than the full URL.
